# Generated by Django 4.0.4 on 2022-06-04 22:08

from django.db import migrations, models
import sweetmoon_django.utils.field_methods


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('last_modify_time', sweetmoon_django.utils.field_methods.UnixTimestampField(auto_created=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', sweetmoon_django.utils.field_methods.UnixTimestampField(null=True)),
                ('username', sweetmoon_django.utils.field_methods.CustomCharField(default=None, max_length=100, null=True)),
                ('nickname', sweetmoon_django.utils.field_methods.CustomCharField(default=None, max_length=50, null=True)),
                ('password', models.TextField()),
                ('salt', sweetmoon_django.utils.field_methods.CustomCharField(default=None, max_length=50, null=True)),
                ('note', models.TextField(null=True)),
                ('phone', sweetmoon_django.utils.field_methods.CustomCharField(default=None, max_length=11, null=True)),
                ('email', sweetmoon_django.utils.field_methods.CustomCharField(default=None, max_length=255, null=True)),
                ('github', models.TextField(null=True)),
                ('last_login_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
